<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerP4j2pzG\testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerP4j2pzG/testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerP4j2pzG.legacy');

    return;
}

if (!\class_exists(testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerP4j2pzG\testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer::class, testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer::class, false);
}

return new \ContainerP4j2pzG\testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer([
    'container.build_hash' => 'P4j2pzG',
    'container.build_id' => '2449a52d',
    'container.build_time' => 1593671809,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerP4j2pzG');
