<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerDarwtLM\testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerDarwtLM/testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerDarwtLM.legacy');

    return;
}

if (!\class_exists(testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerDarwtLM\testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer::class, testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer::class, false);
}

return new \ContainerDarwtLM\testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer([
    'container.build_hash' => 'DarwtLM',
    'container.build_id' => '2da0f785',
    'container.build_time' => 1593670173,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerDarwtLM');
