<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerQO5u4tG\testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerQO5u4tG/testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerQO5u4tG.legacy');

    return;
}

if (!\class_exists(testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerQO5u4tG\testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer::class, testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer::class, false);
}

return new \ContainerQO5u4tG\testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer([
    'container.build_hash' => 'QO5u4tG',
    'container.build_id' => '9121ce62',
    'container.build_time' => 1593601561,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerQO5u4tG');
