<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerPxYOHND\testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerPxYOHND/testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerPxYOHND.legacy');

    return;
}

if (!\class_exists(testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerPxYOHND\testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer::class, testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer::class, false);
}

return new \ContainerPxYOHND\testsAMREU_UserBundle_Test_UserBundleTestingKernelTestDebugContainer([
    'container.build_hash' => 'PxYOHND',
    'container.build_id' => '0fb65406',
    'container.build_time' => 1593764814,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerPxYOHND');
